metabrainz/static/css/styles.less
metabrainz/templates/donations/donate.html

Validating donation amount earlier

---

metabrainz/__init__.py
metabrainz/admin/views.py
metabrainz/model/tier.py
metabrainz/model/token.py
metabrainz/model/user.py
metabrainz/templates/admin/master.html
metabrainz/templates/admin/tokens/index.html
metabrainz/templates/admin/tokens/search.html
metabrainz/templates/admin/users/details.html
metabrainz/templates/admin/users/index.html
metabrainz/templates/admin/wrapper.html
requirements.txt

This is live at http://metabrainz.mbsandbox.org/admin/. Credentials are yoshi/yoshi, as usual.

New admin stuff

---

INSTALL.md
metabrainz/api/decorators.py
metabrainz/api/views.py
metabrainz/config.py.example
metabrainz/static/css/main.less
metabrainz/templates/api/info.html
metabrainz/templates/users/profile.html

API improvements

---

metabrainz/static/css/main.less
metabrainz/templates/base.html

Live at http://metabrainz.mbsandbox.org/.

Construction gifs

---

metabrainz/model/donation.py
metabrainz/model/donation_test.py

https://stripe.com/docs/upgrades?since=2014-12-08#api-changelog

Switch to updated Stripe API

---

metabrainz/model/donation.py

```PLpgSQL
BEGIN;
CREATE TYPE payment_method_types AS ENUM ('stripe', 'paypal', 'wepay');
ALTER TABLE donation ADD COLUMN payment_method payment_method_types;
ALTER TABLE donation DROP COLUMN method;
ALTER TABLE donation RENAME COLUMN contact TO can_contact;
ALTER TABLE donation RENAME COLUMN anon TO anonymous;
END;
```

Schema adjustments

---

metabrainz/static/css/main.less
metabrainz/templates/base.html
metabrainz/templates/index/about.html
metabrainz/templates/index/index.html
metabrainz/templates/navbar.html
metabrainz/templates/users/list.html
metabrainz/templates/users/tier.html
metabrainz/users/views.py
metabrainz/users/views_test.py

Changed all instances of Customers to Supporters

---

metabrainz/static/css/main.less
metabrainz/templates/users/list.html
metabrainz/templates/users/tier.html

Improved 'Supporters' page

---

metabrainz/static/css/main.less
metabrainz/templates/base.html
metabrainz/templates/navbar.html

Updated parts of the interface related to user accounts

---

metabrainz/model/tier.py
metabrainz/model/user.py
metabrainz/templates/users/tier.html

```sql
ALTER TABLE "user" ADD COLUMN in_deadbeat_club BOOLEAN;
UPDATE "user" SET in_deadbeat_club = FALSE;
ALTER TABLE "user" ALTER COLUMN in_deadbeat_club SET NOT NULL;
```

Added 'in_deadbeat_club' flag into User model

---

metabrainz/static/css/main.less
metabrainz/templates/users/profile.html
metabrainz/templates/users/tiers.html

Add a section that gives the user permission or not to use our data (it depends on their account standing). 
Add more details to their profile. The display could be cleaned up a bit.
Also, somewhat OT, allow three lines of description in the tiers overview.

Profile improvements

---

metabrainz/model/tier.py

Fixed tier details in email notification

---

metabrainz/templates/users/signup-commercial.html

Added a note about fields that will be public

---

metabrainz/model/user.py
metabrainz/templates/admin/users/details.html
metabrainz/templates/users/signup-commercial.html
metabrainz/users/forms.py
metabrainz/users/views.py

```sql
ALTER TABLE "user" ADD COLUMN amount_pledged NUMERIC(11,2);
```
*Fixes #105.*

Added amount_pledged column

---

metabrainz/templates/users/signup-commercial.html
metabrainz/users/forms.py
metabrainz/users/views.py

Require all address fields for customers who choose invoicing payment option

---

metabrainz/api/decorators.py
metabrainz/api/views.py
metabrainz/config.py.example
metabrainz/model/access_log.py
requirements.txt

Schema update:
```sql
ALTER TABLE access_log ADD COLUMN ip_address INET;
```
*Fixes #99.*

Using IP addresses for API abuse detection

---

metabrainz/__init__.py
metabrainz/templates/users/tier.html

Added support for line breaks in long tier descriptions

---

metabrainz/templates/users/signup-commercial.html

Added a note about payment process for commercial users

---

metabrainz/donations/paypal/views_test.py
metabrainz/donations/views.py
metabrainz/donations/wepay/views.py
metabrainz/model/donation.py
metabrainz/model/donation_test.py
metabrainz/templates/donations/donate.html

Okay, I think I finally got PayPal to work again. There are some additional things related to testing and logging. And I'm still looking into problems with WePay.
*This branch is live at http://metabrainz.mbsandbox.org/donate/.*

Donation-related updates

---

metabrainz/templates/users/mb-login.html
metabrainz/templates/users/mb-signup.html

Updated text in template describing association with MusicBrainz account

---

metabrainz/model/donation.py
metabrainz/templates/donations/donors.html

```sql
ALTER TABLE donation ALTER COLUMN fee DROP NOT NULL;
```

Make donation fee column nullable

---

metabrainz/model/tier.py
metabrainz/model/user.py
metabrainz/static/css/main.less
metabrainz/templates/users/account-type.html
metabrainz/users/views.py

Check out this work in progress for improving the tiers.

Trying out visual improvements for the tiers page. (WIP)

---

metabrainz/static/css/main.less

Fixed problems with image size in Firefox and IE

---

metabrainz/templates/users/account-type.html
metabrainz/templates/users/profile.html
metabrainz/templates/users/signup-commercial.html
metabrainz/users/forms.py
metabrainz/users/views.py

Mxm feedback fixes

---

metabrainz/users/views.py

Send email confirmation to user after signup form is submitted

---

metabrainz/model/donation.py

```sql
ALTER TYPE payment_method_types ADD VALUE 'bitcoin';
ALTER TYPE payment_method_types ADD VALUE 'check';
```

Two more payment method types

---

metabrainz/model/donation.py

Grouping donations from the same person in get_biggest_donations method

---

metabrainz/__init__.py
metabrainz/donations/views.py
metabrainz/model/donation.py

Updated nag-check endpoint

---

metabrainz/model/donation.py
metabrainz/model/donation_test.py

See https://stripe.com/docs/connect/payments-fees#fees-on-charges.
*I switched to this branch at http://metabrainz.mbsandbox.org/.* :money_with_wings: :money_with_wings: :money_with_wings:

Using balance transaction to get fees for Stripe charges

---

manage.py
metabrainz/model/access_log.py

Disabled operation that causes deadlock

---

metabrainz/templates/index/index.html

Fix a definite article on the homepage

---

metabrainz/__init__.py
metabrainz/admin/views.py
metabrainz/model/user.py
metabrainz/templates/admin/commercial-users/index.html
metabrainz/templates/admin/home.html
metabrainz/templates/admin/users/index.html

Admin section improvements

---

metabrainz/__init__.py
metabrainz/model/access_log.py
metabrainz/templates/admin/users/details.html

*Fixes [MEB-5](http://tickets.musicbrainz.org/browse/MEB-5).*

MEB-5: Added link to user model editor into admin/users/index.html template

---

metabrainz/model/user.py
metabrainz/templates/admin/users/details.html
metabrainz/templates/users/signup-commercial.html
metabrainz/users/forms.py
metabrainz/users/views.py

```sql
ALTER TABLE "user" DROP COLUMN payment_method;
```
*Fixes [MEB-11](http://tickets.musicbrainz.org/browse/MEB-11).*

MEB-11: Removed payment_method column from User model

---

metabrainz/model/user.py
metabrainz/templates/admin/users/index.html

Added `contact_name` and `contact_email`. :mag:
*Related to [MEB-30](http://tickets.musicbrainz.org/browse/MEB-30).*

Additional columns in user search

---

metabrainz/templates/admin/users/details.html
metabrainz/templates/admin/users/index.html

* Updates to search results page
* More links to user editor
*Related to [MEB-30](http://tickets.musicbrainz.org/browse/MEB-30).* :rainbow:

Admin interface improvements

---

metabrainz/templates/admin/commercial-users/index.html

Looks similar to search results now.
*Related to [MEB-30](http://tickets.musicbrainz.org/browse/MEB-30).* :rainbow:

Updated commercial users page in admin interface

---

metabrainz/templates/admin/tokens/search.html
metabrainz/templates/admin/users/index.html

*Fixes [MEB-32](http://tickets.musicbrainz.org/browse/MEB-32).* :rainbow:

Added autofocus attribute to some inputs in admin section

---

metabrainz/templates/admin/users/details.html

*Fixes [MEB-13](http://tickets.musicbrainz.org/browse/MEB-13).* :boom:

Added "Delete" link to user details page

---

metabrainz/model/donation.py

See http://tickets.musicbrainz.org/browse/MEB-1.

MEB-1: Remove "payment_date" column from donation editor interface

---

admin/schema_updates/8.sql
metabrainz/admin/views.py
metabrainz/model/__init__.py
metabrainz/model/token.py
metabrainz/model/token_log.py
metabrainz/model/user.py
metabrainz/templates/admin/stats/overview.html

*Fixes [MEB-31](http://tickets.musicbrainz.org/browse/MEB-31).*

MEB-31: Token change log

---

metabrainz/admin/views.py
metabrainz/model/token_log.py
metabrainz/templates/admin/stats/overview.html
metabrainz/templates/admin/stats/token-log.html

*Fixes [MEB-31](http://tickets.musicbrainz.org/browse/MEB-31).*

MEB-31: Added a way to view all records in token change log

---

admin/schema_updates/10.sql
metabrainz/admin/views.py
metabrainz/model/user.py
metabrainz/templates/admin/commercial-users/index.html
metabrainz/templates/admin/home.html
metabrainz/templates/admin/users/details.html
metabrainz/templates/admin/users/index.html
metabrainz/templates/users/profile.html

*Fixes [MEB-35](http://tickets.musicbrainz.org/browse/MEB-35).*

MEB-35: New customer state: waiting

---

metabrainz/model/donation.py

*Fixes http://tickets.musicbrainz.org/browse/MEB-41.*

MEB-41: Allow to specify editor name when adding a donation manually

---

metabrainz/users/views.py
requirements.txt

This should fix http://sentry.roman.zone/sentry/meb-production/group/70/.

Check if user already exists before trying to create a duplicate account

---

admin/schema_updates/11.sql
bootstrap.sh
metabrainz/admin/views.py
metabrainz/model/user.py
metabrainz/templates/admin/users/details.html
metabrainz/templates/users/profile.html

Just like `active`, but can't get access to tokens. :no_good:

New user state: limited

---

metabrainz/templates/index/contact.html

Related to [MBS-8588](http://tickets.musicbrainz.org/browse/MBS-8588).

More information on contact page + agreement button

---

metabrainz/templates/donations/donate.html

Fixes http://tickets.musicbrainz.org/browse/MEB-43.
cc: @mayhem, @reosarevok

MEB-43: Make text on donation page more general

---

metabrainz/templates/index/contact.html

*Related forum topic: http://forums.musicbrainz.org/viewtopic.php?pid=32153.*
cc: @reosarevok, @mayhem

Hide only email address on contact page

---

metabrainz/templates/index/team.html

* Make 'Freso' part of the name.
* Add links to MusicBrainz and GitHub profiles.

Add some changes to my (Freso's) entry.

---

metabrainz/templates/index/projects.html

accidentally had "by providing is a platform"

project page -- fix typo in CB blurb

---

metabrainz/templates/index/contact.html

Feel free to suggest different wording for this section.

MEB-48: add Forums to contact page

---

metabrainz/templates/index/contact.html

Link to prod. musicbrainz.org instead.

Fix link to beta.musicbrainz.org.

---

metabrainz/templates/index/contact.html

See https://community.metabrainz.org/t/easy-link-to-irc-for-bug-report/57333

Add IRC webchat link to Contact page.

---

bootstrap.sh
metabrainz/mail.py
metabrainz/model/payment.py
metabrainz/payments/receipts.py
metabrainz/payments/stripe/views.py
metabrainz/templates/payments/donate.html

*This also fixes several small donation-related issues.*

Fix issue with incorrect headers in receipt emails

---

metabrainz/static/css/main.less
metabrainz/templates/index/index.html
metabrainz/views.py

MEB-52: Improvements to the way featured users are displayed on homepage

---

metabrainz/payments/views.py
metabrainz/payments/views_test.py
metabrainz/templates/payments/cancel_recurring.html
metabrainz/templates/payments/donate.html
metabrainz/templates/payments/payment.html

http://tickets.musicbrainz.org/browse/MEB-27

MEB-27: Provide information about canceling recurring payments

---

metabrainz/__init__.py
metabrainz/static/robots.txt

http://tickets.musicbrainz.org/browse/MEB-14

MEB-14: Add robots.txt file

---

metabrainz/templates/users/signup-commercial.html
metabrainz/templates/users/signup-non-commercial.html
metabrainz/users/views.py

http://tickets.musicbrainz.org/browse/MEB-17

MEB-17: Show MB username during signup process

---

metabrainz/users/views.py

http://tickets.musicbrainz.org/browse/MEB-9

MEB-9: Check if user already exists before creating an account

---

metabrainz/templates/index/about.html
metabrainz/templates/index/team.html

* Reflect @Freso's new location
* Reflect recent changes to the board
* Some clean-up in the code for the board information

Update various information on metabrainz.org

---

requirements.txt

*Changelog: https://flask-admin.readthedocs.io/en/latest/changelog/.*

Update Flask-Admin requirement to 1.4.2

---

metabrainz/templates/admin/users/details.html

User page cleanup

---

metabrainz/templates/payments/donate.html
metabrainz/templates/reports/financial_reports/index.html

Fix more minor bugs introduced by localisation

---

docker/push.sh

https://docs.docker.com/engine/reference/commandline/push/

Allow to specify tag for images pushed to the Docker Hub

---

metabrainz/admin/views.py
metabrainz/templates/admin/payments/list.html

MEB-75: Add filters to show only payments or donations in the admin view

---

docker/prod/uwsgi.ini

https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#a-note-on-python-threads

Run uWSGI with threads enabled since it's required by Raven

---

metabrainz/model/payment.py
metabrainz/model/payment_test.py
metabrainz/payments/__init__.py
metabrainz/payments/paypal/views.py
metabrainz/payments/views.py
metabrainz/payments/views_test.py
metabrainz/templates/payments/donate.html
metabrainz/templates/payments/payment.html
metabrainz/templates/payments/payment_base.html
metabrainz/templates/payments/payment_selector.html
requirements.txt

*This is based on changes done for MEB-90.*
Test version with this code is deployed at https://test.metabrainz.org/.

MEB-91: EUR support for other types of payments and additional improvements

---

README.md
docker/Dockerfile.dev

Documentation for CSS builds in development

---

metabrainz/templates/navbar.html

Should help with the confusion.
cc @eebigger, @reosarevok

Add a separate link for logging in into the navbar

---

admin/sql/create_db.sql
admin/sql/create_test_db.sql

See [LB-244](https://tickets.metabrainz.org/browse/LB-244) for details.

Use NOSUPERUSER instead of NOCREATEUSER

---

docker/Dockerfile.dev
docker/docker-compose.dev.yml
metabrainz/__init__.py
metabrainz/utils.py

Also, removed the `runserver` command from the dockerfile and moved it into `docker-compose.yml` for consistency with LB and MsB etc.

MEB-98: Add logging of config values and git commit on init

---

.gitignore
docker/push.sh
metabrainz/__init__.py
metabrainz/utils.py

Improve the startup logging and fix the broken git version logging

---

metabrainz/templates/index/about.html

just a small typo that I noticed! 😄

fix: add space between words

---

metabrainz/__init__.py
metabrainz/views_test.py
requirements.txt

Also, add a test to ensure that it works

Initialize Flask-DebugToolbar correctly

---

metabrainz/templates/index/privacy.html

Remove Google Analytics from our privacy policy since we no longer use it

---

metabrainz/templates/index/gdpr.html
metabrainz/templates/navbar.html
metabrainz/views.py

Add GDPR compliance statement

---

metabrainz/templates/index/code-of-conduct.html

Not much else to say -- as per discussion during our weekly community meeting.

Add a "use gender neutral language" to our CoC.

---

metabrainz/users/views.py

So the flow goes
clicks sign-in from homepage -> login with musicbrainz -> gives access on MB -> gets asked to sign up and choose tier if new user.

Add info message for new users who've clicked the sign in button

---

metabrainz/templates/users/supporters-list.html

https://tickets.metabrainz.org/browse/MEB-109

MEB-109: Add a link to become supporter from the supporters page

---

metabrainz/templates/users/signup-commercial.html

https://tickets.metabrainz.org/browse/MEB-71

MEB-71: Add explanation to company description

---

metabrainz/__init__.py
metabrainz/admin/views.py
metabrainz/admin/views_test.py
metabrainz/model/access_log.py
metabrainz/model/access_log_test.py
metabrainz/model/user.py
metabrainz/templates/admin/stats/top-ips.html

Adds a fairly simple new admin view to see who the top IP addresses are in the last week.

Create a new stats view that shows the most active IP addresses

---

metabrainz/__init__.py
metabrainz/admin/views.py
metabrainz/admin/views_test.py
metabrainz/model/access_log.py
metabrainz/model/access_log_test.py
metabrainz/model/user.py
metabrainz/templates/admin/stats/top-ips.html
metabrainz/templates/admin/stats/top-tokens.html
test.sh

The same as the previous PR, but for top tokens. Also add test.sh and this version uses column names and not column indexes.

Add top token stats

---

metabrainz/admin/views.py
metabrainz/templates/admin/stats/top-ips.html
metabrainz/templates/admin/stats/top-tokens.html

Not super pretty but the target audience is limited to 1 person. :) :)

Add HTML elements to view 1, 7, 30 views of the top reports

---

metabrainz/model/payment.py
metabrainz/templates/admin/payments/list.html

(and one annoying page header)

Change boolean text string to an actual boolean value.

---

metabrainz/model/payment.py

Another quick one to deal with another instance of boolean problems...

Fix another problem with passing boolean values to SQLA

---

metabrainz/users/views.py
metabrainz/users/views_test.py

A simple arg checking fix, with test improvement.

Fix invalid tier ise

---

metabrainz/users/views.py

Another sentry error -- not sure how to add a test for it. Not sure it is worth it.

Raise a proper bad request when the login attempt fails.

---

metabrainz/__init__.py
metabrainz/admin/views.py
metabrainz/admin/views_test.py
metabrainz/model/user.py
metabrainz/templates/admin/stats/supporters.html

I've added a new view that shows our active customers and the amount they have pledged and then the total for all. This view shows what our monthly income should be.

Add current supporters page

---

Dockerfile
docker/Dockerfile.dev
docker/pg_custom/Dockerfile

and removing the pg-client from the web container. Should be ready for the pg upgrade.

Upgrade PG to 12.3

---

metabrainz/templates/index/code-of-conduct.html

https://tickets.metabrainz.org/browse/ORG-40

ORG-40: Add anti‐sockpuppet clause to the Code of Conduct

---

metabrainz/templates/index/gdpr.html

Remove references to BigQuery and tickets that are no longer relevant.

---

metabrainz/templates/index/team.html

Update the team page to reflect lucifer's status as a team member.

Update lucifer's info

---

metabrainz/templates/index/contact.html

We no longer require registration. Also updating links to the freenode chats while at it.

MEB-114: Update IRC information

---

metabrainz/templates/index/sponsors.html

As of today, their last donation was Dec 2019 and total was $470,689.15 per https://metabrainz.org/donors?order=amount

MEB-119: Update Google's donation amount

---

.github/workflows/deploy-image.yml

See https://github.com/metabrainz/listenbrainz-server/pull/1498

Use tag to set GIT_COMMIT_SHA

---

metabrainz/model/access_log.py

Change looks simple but will need to test ensure it works.

MEB-19: Add more detail to over limit emails

---

metabrainz/templates/index/team.html

Not really that junior anymore, and I'm leaving WMEE, so I thought I'd update this a bit :)

Update reo's profile

---

metabrainz/templates/index/team.html

Add chosen pronoun for CatQuest

---

requirements.txt

Update reportlab to a safe version.

Update reportlab for SEC-826

---

README.md

According to @mayhem this is supposed to be init-db - and indeed that does work.

Fix typo in suggested command

---

admin/schema_updates/18.sql
admin/sql/create_types.sql
metabrainz/model/user.py

Fix test and add critiquebrainz project type.

Dataset Page improvements

---

metabrainz/model/dataset.py

The enum was missing from the code.

Add CB to the python enum

---

metabrainz/templates/index/datasets/download.html

Adding the DK dotsrc mirror and changing other links to https.

Add dotsrc

---

metabrainz/templates/index/datasets.html
metabrainz/templates/index/datasets/postgres-dumps.html
metabrainz/templates/index/datasets/signup.html
metabrainz/templates/users/account-type.html

Improve text according to aerozols's improvements

---

metabrainz/invoices/send_invoices.py

I never got output because default log level doesn't show info. Not sure why that used to work, but ok.

Use warn to print output, not info.

---

docker/prod/uwsgi.ini

LB's uwsgi.ini configuration is more robust and plays well with consul too.

Update MeB uwsgi.ini to match LB uwsgi.ini

---

requirements.txt

Given the latest security advisory...

Update urllib for SEC-1158

---

requirements.txt

Copying the same setup from @amCap1712's fixes for LB.

SEC-1183: werkzeug update

---

metabrainz/templates/base.html
metabrainz/templates/index/team.html

* Add our new channels on Mastodon, Bluesky, and Instagram.
* Update the title of Twitter links.

 Update our active social channels

---

metabrainz/templates/index/about.html
requirements.txt

And update one dependency. Cake.

Add Hazel Savage as our director.

---

metabrainz/templates/base.html

Follow the [change announced on IRC](https://chatlogs.metabrainz.org/libera/metabrainz/msg/5312672/).
Reference: https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial

Follow updating Bluesky handle with our domain

---

metabrainz/admin/quickbooks/views.py
metabrainz/templates/quickbooks/index.html

Quickbooks changed something on how invoice numbers are created... and broke something very simple. This PR makes the invoice number assignment automatic now based on the highest invoice number found.

Fix invoice numbers

---

admin/schema_updates/2024-09-09-add-editor-id-to-payment.sql
admin/sql/create_tables.sql
manage.py
metabrainz/model/access_log_test.py
metabrainz/model/payment.py
metabrainz/model/supporter.py
metabrainz/supporter/copy_mb_row_ids.py
metabrainz/supporter/musicbrainz_login.py
metabrainz/supporter/views.py

Import musicbrainz row ids and add row id support to supporter and payments table.

Add musicbrainz row ids

---

metabrainz/templates/payments/donate.html
metabrainz/templates/payments/payment.html

This reverts commit 2a103a4fbd5705e4377f536e18a9dba6fc824f40.

Add paypal buttons back to donation and payment page

---

requirements.txt

Bump jinja2: https://tickets.metabrainz.org/browse/SEC-1356

SEC-1356: fix CVE-2024-56201

---

frontend/css/main.less
frontend/css/theme/variables.less

As per our discussion, upping font size to 16px, save for the navbar. for reasons.

Increase font size

---

requirements.txt

Fix jinja CVE

---

metabrainz/invoices/send_invoices.py
metabrainz/model/access_log.py
metabrainz/model/payment.py
metabrainz/model/supporter.py
metabrainz/model/token.py
metabrainz/model/token_log.py

Replaced depricated methods
1. datetime.utcnow() with datetime.now(timezone.utc)
https://docs.python.org/3/library/datetime.html#datetime.datetime.now
2. logger.warn() with logger.warning()
https://docs.python.org/3.11/library/logging.html#logging.Logger.warning

Clean-up PR

---

metabrainz/db/notification.py
metabrainz/mail.py
metabrainz/notifications/views.py

Refactored code to send non important notifications.
Added a function that returns notifications which are to be sent to users with digest disabled.

Send notifications immediately to users with digest disabled
