metabrainz/api/decorators.py
metabrainz/api/views.py

I think there's no need to transfer all our fancy HTML on default error pages to API users.

Return shorter responses from the API when errors occur

---

metabrainz/donations/paypal/views.py
metabrainz/donations/paypal/views_test.py
metabrainz/model/donation_test.py

IPN endpoint should work better now. Though I still can't get my payments to go though in sandbox. Every single one is `pending`. `pending_reason` is set to `unilateral` which, [according to docs](https://developer.paypal.com/webapps/developer/docs/classic/ipn/integration-guide/IPNandPDTVariables/#id091EB04C0HS), means that payment was made to an email address that is not yet registered or confirmed. I can't find a solution to this.

Fixed PayPal IPN endpoint

---

metabrainz/templates/index/index.html

Note that the AcousticBrainz site is not accessible over TLS.

Include external links in the carousel

---

metabrainz/api/views.py
metabrainz/api/views_test.py

This PR creates a nagios style endpoint for checking the completeness of validity of the current set of replication packets. Nagios wants to have a single line of output that starts with OK, WARNING, CRITICAL or UNKNOWN; the rest of the line is for humans to consume and should be telling of that the problem is.
This PR checks to make sure that all files are there and that the latest file is less then 4 hours old. We may be able to tighten this check, but lets leave it there for now.

Replication check

---

README.md
metabrainz/cache.py
metabrainz/donations/receipts.py
metabrainz/static/css/theme/boostrap/responsive-utilities.less
metabrainz/static/css/theme/boostrap/scaffolding.less
metabrainz/templates/base.html
metabrainz/templates/donations/donate.html
metabrainz/templates/index/about.html
metabrainz/templates/index/index.html
metabrainz/templates/index/projects.html
metabrainz/templates/index/sponsors.html
metabrainz/templates/index/team.html

Also snuck in an update for a wiki.mb.o link to point to mb.o/doc/ instead.

Change HTTPS-capable http:// links to use https:// instead

---

metabrainz/templates/index/index.html

I always found it weird that clicking on one of the supporters lead to the list of sponsors, so change it.
Note: I didn't actually test this.

Link the supporter logos to the supporters page

---

metabrainz/api/views/musicbrainz.py
metabrainz/api/views/musicbrainz_test.py

This caused the API to display incorrect number of the latest packet.

MEB-63: Fix sorting of replication packets

---

metabrainz/views.py
metabrainz/views_test.py

/about/customers link is a dead link and it should be redirected to /supporters link 
Issue Link : https://tickets.metabrainz.org/browse/MEB-50

MEB-50: Redirecting about/customers to /supporters page

---

metabrainz/templates/index/contact.html

https://tickets.metabrainz.org/browse/MEB-81
MusicBrainz.org links to metabrainz.org/contact for it's "Contact Us" link, but the page didn't actually reference the main IRC channel for MusicBrainz users.

MEB-81: Add #musicbrainz IRC channel to /contact

---

metabrainz/templates/payments/donate.html

I didn't test this.
I haven't done this in years.
I might have just broken everything.
Buyer beware.

Prevent literal <em> from being displayed

---

admin/schema_updates/15.sql
admin/schema_updates/16.sql
admin/sql/create_tables.sql
admin/sql/create_types.sql
metabrainz/testing.py

`15.sql` is already applied. `16.sql` is required to make payments function after changes are reverted (all payments would be `USD` by default just as they were before).

Currency-related schema changes

---

consul_config.py.ctmpl

This allows configuring name of the environment for a deployed version of the MetaBrainz website. Error reports can then be filtered by environment name in the Sentry UI.

Retrieve name of the Sentry environment from Consul

---

metabrainz/__init__.py

Only read the consul configuration file and nothing else if we're running in production. The steps that CustomFlask takes to find a configuration file can hide problems in production. A race condition to find the consul config file and this issue caused an hour long metabrainz.org outage, so I'm keen to really ensure this is fixed.

Only use consul config in production

---

metabrainz/templates/index/code-of-conduct.html
metabrainz/templates/index/privacy.html
metabrainz/templates/index/social-contract.html
metabrainz/templates/navbar.html
metabrainz/views.py
metabrainz/views_test.py

This RP attempts to move the MusicBrainz specific privacy policy/CoC/social contract and create a MetaBrainz umbrella version of each of those. Making one policy that covers all of our projects is unrealistic, so the goal it to have the general points that are common to all projects under the MetaBrainz version of these documents. This can be seen in the Code of Conduct now and I suspect that as we flesh out the PP and social contract we may want project specific extensions in the future.
Code of Conduct:
Parts of the MusicBrainz Code of Conduct move to MetaBrainz at https://test.metabrainz.org/code-of-conduct and the MB CoC gets edited to: https://wiki.musicbrainz.org/Code_of_Conduct
Privacy Policy:
The PP on MB moves to http://metabrainz.org/privacy and gets an update: …

Code of Conduct, Privacy Policy and Social Contract consolidation

---

README.md
default_config.py
metabrainz/api/views/musicbrainz.py
metabrainz/api/views/musicbrainz_test.py
metabrainz/templates/api/info.html

The daily/weekly packets haven't been updating since some time in 2016, and I recall @mayhem giving the OK to only support hourly ones, but lemme know if you'd still like to document/include them in the API.

Document incremental JSON dumps API, remove daily/weekly packets

---

metabrainz/templates/index/contact.html

This can hopefully be reverted soon enough, but whether the channels are in `+r` or `+zq $~a` mode people will need to register to talk in the channels. The spam attack has been going for a month now, so let's be up front about the current reality.
(This is mostly a copy/paste of the note I added on the wiki page: <https://wiki.musicbrainz.org/index.php?title=Communication%2FIRC&type=revision&diff=72851&oldid=72850>)

Add note about registration requirement for IRC

---

metabrainz/static/css/main.less
metabrainz/templates/base.html
metabrainz/templates/index/datasets.html
metabrainz/templates/navbar.html
metabrainz/views.py
metabrainz/views_test.py

The following changes have been made: 
1. Created a two column layout
2. Made the logos a bit smaller
3. Made the text flow around the logos
4. Streamlined the headings -- there is a lot of duplication -- not each heading needs to have the "Data Dumps" in.
5. Streamlined the descriptions 
6. Added a nice catch all commercial use statement at the top, with basically this sentiment: "we ask commercial users to support us in order to help fund the creation and maintenance of these datasets."

 MEB-100: Add a new datasets page

---

requirements.txt

GitHub said there wasn't a fix, but looks like 1.5.3 fixes it (https://flask-admin.readthedocs.io/en/latest/changelog/#id1)

Upgrade flask admin to fix SEC issue

---

metabrainz/templates/index/gdpr.html
metabrainz/templates/index/privacy.html

***Not** part of the Google Code-in (GCI) competition*
This is just a quick pull request to fix some minor typos in the GDPR Compliance Policy and the Privacy Policy.
Related to #338 but I don't think any of our changes overlap
The changes include:
- Adding a closing `</a>` tag
- Substituting "which is becomes processing" for "which involves processing"
- Substituting "the minor feature of browsers analysis" for "browser" (no 's')
- Substituting "Our project's web pages" for "Our projects' web pages" (note position of apostrophe) because Metabrainz has many projects, each of which have their own web pages
I just also wanted to raise some other very minor points (not addressed by this PR):
- Some of the lines in the file have a trailing space, but others don't
- The spelling of some …

Fix minor typographical errors etc. in GDPR, Privacy policies

---

metabrainz/templates/payments/donate.html

Reciprocally, a link should be added from <https://github.com/sponsors/metabrainz> to <https://metabrainz.org/donate>.

Add GitHub Sponsors to other ways to donate

---

Dockerfile
docker/Dockerfile.dev
docker/Dockerfile.test
requirements.txt

Upgrade to the latest version of pip and brainzutils. BU now uses open-ended versions, hence we pin all the versions here. The change in how flask_uploads dependency is specified has been made to avoid errors in the development mode.

Upgrade pip, brainzutils and pin package versions

---

metabrainz/templates/reports/financial_reports/index.html

Updating reporting frequency to reflect 2017 update: 
"Please note that starting in 2017 we reduced the frequency with which we post our reports in order to reduce the amount of time spent on accounting."
(I'm guessing that Rob targets first week... even if not, this is still most likely more accurate 😁)

MEB-118: Finances release on quarterly cycle

---

package.json

lessc v4 has suddenly started to err while building the Docker image. See https://gist.github.com/mayhem/afbd5da10f003013044a8b7e704fcd7d . I think this might be the issue https://github.com/less/less.js/issues/3608 we are facing. That still doesn't explain why it worked the last time. Anyways, downgrade to v3 for now.

Downgrade lessc to v3

---

metabrainz/templates/index/team.html

These are the new nicks of some of the team members on Libera.Chat. Will keep updating as the remaining members move to the new network,

Update nicks of team members as on Libera.Chat

---

.github/release-drafter.yml
.github/workflows/deploy-image.yml
.github/workflows/release-drafter.yml
.github/workflows/tests.yml
docker/Dockerfile.test
docker/docker-compose.test.yml
test.sh

Adding action workflows for building production images, running tests and creating release notes. We are now moving to a date based tag and release as in other *Brainz. We should also remove the Jenkins job after merging this.

Add actions workflows

---

metabrainz/admin/views.py
metabrainz/payments/views.py
metabrainz/utils.py

and use the default value instead if param is not a valid integer
A bunch of errors related to this showed up in sentry, hence fixing it.

Validate integer query params

---

config.py.example
consul_config.py.ctmpl
metabrainz/__init__.py
metabrainz/payments/stripe/views.py
metabrainz/payments/views.py

We don't need a STRIPE_KEYS and another STRIPE_TEST_KEYS. Just keep one and put the keys you are using there. For consul config this means, that test.meb config contains the test keys only while the prod one uses live keys only.

Simplify stripe keys configuration

---

metabrainz/payments/stripe/views.py

Rob had pointed out that the earlier checkout showed a human readable description in the Stripe Dashboard. This PR adds back the description. It is shown both to the user and in the dashboard.

Add description to show to user and in stripe dashboard

---

requirements.txt

WTForms 3.* moves arounds some fields so imports need to be updated, possible Flask-WTF may need to be updated as well to be compatible with it. For now, pin the latest 2.* version.

Pin WTForms version

---

metabrainz/templates/index/privacy.html

The existent privacy policy is a little flippant and not very clear about who may actually have access to our infrastructure. This PR aims to clear this up.

Improve the clarity of the Privacy Policy exemption

---

metabrainz/api/views/musicbrainz.py
metabrainz/api/views/musicbrainz_test.py

Since the last schema change, MB now generates dbmirror2 replication packets, which exist in the same volume and have a '-v2' suffix after the packet number.
This commit adds initial support for fetching such packets to help me test them with replication and JSON dumps.
For now I just made it so that you fetch them how they're named on disk (with '-v2' suffix) but we could alternatively add an API subpath like /api/musicbrainz/v2/ if that's desirable.

Support fetching replication v2 packets

---

metabrainz/admin/quickbooks/views.py
metabrainz/invoices/send_invoices.py

These two minor fixes fix a problem where copied invoices contained incorrect DeliveryInfo (which is now reset to default for each new invoice) and where a do no send invoice was actually sent, because of a missing continue statement.

Minor fixes (and fix a long standing bug) for the send invoices feature.

---

manage.py
metabrainz/invoices/send_invoices.py

This part was still missing, but now we can send invoice reminders by just running one command. Much easier!
Much like sending invoices, but a slightly different workflow.

Send invoice reminders

---

metabrainz/templates/index/code-of-conduct.html

It makes sense to have a straight link from "how to behave" to "what do we do if someone does not".
Mirrors https://github.com/metabrainz/.github/pull/4

Link CoC to conflict policy doc

---

requirements.txt

Bump sentry-sdk from 0.20.3 to 1.14.0

---

metabrainz/static/css/main.less
metabrainz/templates/index/datasets.html

On mobile, the fixed height css of the dataset page cards becomes an issue and text overlaps outside the cards.
Using flexbox instead (because flexbox is the answer to all my problems) we can make the cards extend to be the same height as their neighbors, but also have that height be dynamic.

Fix dataset cards layout

---

requirements.txt

urllib3 2.0 requires newer versions of OpenSSL on the OS. For now, pin an older version.

Pin urllib3==1.26.16 to fix actions build

---

metabrainz/reports/annual_reports/files/2018/content.html
metabrainz/templates/base.html
metabrainz/templates/navbar.html
metabrainz/templates/reports/annual_reports/view.html

It follows the comments to the pull request #412 (to replace it).
- Add archive notice to annual reports
- Reword the menu item “Annual Reports” (and same strings) as “Archived Annual Reports”

Archive annual reports

---

metabrainz/templates/index/team.html

New IRC nick, new name, slight bio changes.
Untested but nothing should break stuff here.

Update CatQuest's team info

---

metabrainz/model/payment.py
metabrainz/payments/stripe/views.py
metabrainz/templates/payments/donate.html

The current implementation is able to create subscriptions but not cancel them. Cancelling stripe subscriptions requires us to store the donor's stripe customer id. This means that we'll need auth for stripe recurring subscriptions. Otherwise, we cannot be sure that a user's subscription is not messed up with by someone else. Before we go ahead to implement this, we should consider if this added complexoty is worth it.

Subscriptions using Stripe

---

metabrainz/templates/index/privacy.html

Additionally explain that the default email address is a no-reply since this behavior depends on the settings for our Weblate instance and thus this is not specified in the generic Weblate page for legal terms.

Update privacy policy for switching to Weblate

---

.dockerignore
docker/docker-compose.dev.yml
docker/prod/uwsgi.ini
frontend/img/.gitignore
metabrainz/admin/forms.py
metabrainz/templates/admin/users/details.html
metabrainz/templates/index/bad-customers.html
metabrainz/templates/index/index.html
metabrainz/templates/users/account-type.html
metabrainz/templates/users/supporters-list.html
metabrainz/templates/users/tier.html

In #413, I had renamed the directory in the MeB.org codebase but I was unaware that there was a mount at the exact location in docker-server-configs. While investigating a related error, I discovered this issue.
I will need to check if some logos have been irretrievably lost since this erring code has been in production for about 2 months.

Fix user_logos directory location

---

.github/workflows/tests.yml

Running with docker image caching is slower than downloading the image from docker hub itself.

Remove caching from tests action

---

metabrainz/templates/users/account-type.html

This fixes the syntax which appears to have gotten broken 6 years ago during 12246c6

Non-commercial donate link was broken

---

.github/workflows/tests.yml

Essentially applying the same changes as in https://github.com/metabrainz/critiquebrainz/pull/495 since I believe the workflow was copied from CB.
I noticed this test workflow has been consistently failing* even thought the testing step succeeds. The action that is supposed to publish the test results is failing due to permissions issues.
I'm now adding the required permissions to allow the workflow to write checks and comments on pull requests, as well as updating to a newer version of the action.
* see failures like so: https://github.com/metabrainz/metabrainz.org/actions/runs/6574602419/job/17898828849#step:7:31

Update CI test results workflow

---

metabrainz/admin/quickbooks/quickbooks.py
metabrainz/invoices/send_invoices.py

Not sure why this died now, but sending invoices no longer worked. Removing it and everything works. Odd.

enable_global no longer exists

---

metabrainz/templates/users/profile.html

People can get confused as to what waiting status means, so lets spell it out and make the page a little more clear and readable overall.

Improve the text on the profile page for commercial users

---

metabrainz/templates/index/privacy.html

Two small updates to our [Privacy Policy](https://metabrainz.org/privacy):
1. It explicitly mentions web API calls in the paragraph about server logs. It comes after a [user’s question on IRC](https://chatlogs.metabrainz.org/libera/metabrainz/msg/5250667/).
2. <del>It drops FTP as we don’t use it anymore, datasets now have to be downloaded from web servers through HTTPS even though `ftp` remains in a couple of subdomain names for now.</del>

Clarify Privacy Policy about web API

---

Dockerfile
docker/prod/consul-template-uwsgi.conf
docker/prod/uwsgi.ini

We fixed the `bind(): Address already in use [core/socket.c line 769]` error using `exit-on-reload = true` in uWSGI configuration. However, this prevents graceful reloading.
I did some further investigation as noted in metabrainz/artwork-redirect#46 and have a better fix in mind now.
For the command field in exec block of consul template configuration, use array format. This executes the command directly without spawning a shell wrapper or setting a process group id. Both of which will interfere with forwarding signals to the uWSGI process.
This also needs a newer version of consul-template. So upgrading to a newer base image.

Upgrade python, consul-template, uWSGI

---

metabrainz/templates/index/gdpr.html

"which is becomes" is clearly wrong, but I wasn't sure "which is" or "which becomes" was a lot better, so changing to "which involves". Reported at support.

Fixing small wording mess

---

frontend/css/main.less
metabrainz/templates/index/projects.html

Remove AcousticBrainz and MessyBrainz from:
https://metabrainz.org/projects
This pull moves them to a 'Past Projects' section instead of removing them, as suggested by yvanzo in: https://github.com/metabrainz/metabrainz.org/pull/449

MEB-143: Update projects page v2

---

metabrainz/templates/payments/donate.html

This enables us to take EUR donations again. Hopefully we can get a Stripe EUR account soon.

Make EUR donations go to USD paypal account.

---

metabrainz/model/payment.py
metabrainz/model/payment_test.py

Stripe's API probably changed sometime ago breaking one time transaction logging webhook.
It never worked for subscriptions because we forgot to add it to the webhook configuration in the stripe dashboard.

Fix logging stripe one time charge transactions

---

config.py.example
consul_config.py.ctmpl
metabrainz/__init__.py
metabrainz/model/payment.py
metabrainz/model/payment_test.py
metabrainz/payments/stripe/views.py
metabrainz/payments/views.py
metabrainz/templates/payments/donate.html
metabrainz/templates/payments/payment.html
metabrainz/templates/payments/payment_base.html

The EUR account is different from the USD account and hence using a different set of API keys.

Support EUR payments in stripe

---

metabrainz/payments/receipts.py

Not much else to say, our donation/payment PDFs still have the old address.

Update the address on donation receipts

---

metabrainz/model/payment.py
requirements.txt

To fix vulnerability CVE-2024-40647

Update sentry sdk

---

metabrainz/templates/payments/cancel_recurring.html
requirements.txt

This had a PayPal link which, as far as I can tell, was meant to dispute one-off payments (so, not what we wanted at all), and it didn't mention what to do for Stripe payments (our primary choice at the moment) at all.
Updated the PayPal link to one that is at least about cancelling automatic payments (it's from PayPal US but I'd hope a similar process applies elsewhere), and mentioned that users should contact us if they want their Stripe payment cancelled.
Tested locally, seems to work fine.

MEB-163: Update the docs for cancelling payments

---

README.md
metabrainz/babel.cfg
metabrainz/messages.pot
metabrainz/templates/base.html
metabrainz/templates/index/contact.html
metabrainz/templates/index/social-contract.html
metabrainz/templates/index/team.html

As mentioned by mayhem at the summit, updated "IRC" references to "Chat" or "ChatBrainz" references and changed the relevant links.
Will need testing, sorry, but hopefully this is most of the work done.

Replacing "IRC" with "Chat" or "ChatBrainz"

---

metabrainz/payments/views.py

Calling the nag-check from the ListenBrainz website results in a CORS error. I proposed adding the crossdomain decorator to fix that, confirmed by rob: https://chatlogs.metabrainz.org/libera/metabrainz/2024-11-28/?msg=5404970&page=1

Add @crossdomain decorator to nag-check endpoint

---

frontend/css/main.less
frontend/css/theme/variables.less

All text should now be #1e1e1e:
This meets MetaBrainz design guidelines.

MEB-165: Make fonts as dark as allowed as per our guidelines.

---

metabrainz/messages.pot
metabrainz/templates/payments/donate.html

Apparently, even though a donor only enters their username from the donate page, their real name is also published as per their billing info unless the donation is anonymous. While "your name" is indicated under the anonymous checkbox, given there's nothing indicating your real name will be used at all, this is only easily understandable as "your username" which you are providing. Just to make sure, I asked my wife what she thought would get published by checking the form and she just said "well, that username there, right?".
It's even more confusing given just under the form we say "The personal information provided to the MetaBrainz Foundation during the donation process will not be shared with anyone" - most people, without more information being provided, would I think assume that …

MEB-167: Clarify name in donations means real name 

---

admin/schema_updates/2025-07-22-add-notification_sent-to-notification.sql
admin/sql/create_tables.sql
metabrainz/db/notification.py
metabrainz/model/notification.py

Instead of using `read` column to mark notifications as sent, added a column `notification_sent` which can be marked as true after sending a notification.

Add notification_sent flag
